#!/bin/bash
# Complete deployment script for Vercel + Railway

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     YIHE International Trade Services - Live Deployment        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Your website is ready to go live! Follow these steps:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Deploy Backend (Railway) - 5 minutes"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://railway.app/dashboard"
echo "2. Click: New Project → Deploy from GitHub"
echo "3. Select: sajidsallu13-sudo/yihe-international-trade-site"
echo "4. Add: PostgreSQL plugin"
echo "5. Configure Backend Service:"
echo "   - Name: yihe-backend"
echo "   - Start Command: node server/index.js"
echo "   - Environment: DATABASE_URL (auto from Postgres)"
echo "6. Click: Deploy"
echo "7. Copy: Backend URL (shown in Railway dashboard)"
echo "   Example: https://yihe-backend.railway.app"
echo ""
echo "⏳ WAIT: Railway deploys (usually 2-3 minutes)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Deploy Frontend (Vercel) - 5 minutes"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Click: Add New → Project"
echo "3. Select: sajidsallu13-sudo/yihe-international-trade-site"
echo "4. Framework: Next.js (auto-detected)"
echo "5. Build Settings (keep defaults):"
echo "   - Build Command: npm run build:frontend"
echo "   - Output Directory: .next"
echo "6. Environment Variables:"
echo "   - NEXT_PUBLIC_API_URL: (paste your Railway backend URL from Step 1)"
echo "7. Click: Deploy"
echo ""
echo "⏳ WAIT: Vercel builds and deploys (usually 2-3 minutes)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Your Website is LIVE! 🎉"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Frontend URL: https://yihe-international-trade-site.vercel.app"
echo "Backend API: https://<your-railway-backend-url>"
echo ""
echo "✅ Test your website:"
echo "   - Visit the frontend URL"
echo "   - Fill out contact form"
echo "   - Check if it saves to database"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "GitHub Repository"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📌 https://github.com/sajidsallu13-sudo/yihe-international-trade-site"
echo ""
echo "Done! Your YIHE website is now live! 🚀"
